version: '3.8'

services:
  chatbot-ui:
    build: .
    ports:
      - "80:80"
    environment:
      - API_URL=http://backend:5000
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build: ../
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=Kenwell.py
    restart: unless-stopped
