- hosts: localhost
  gather_facts: yes
  become: yes
  vars_files:
    - secret.yml
  tasks:
    - name: Ping localhost
      ansible.builtin.ping:

    - name: Display company configuration
      ansible.builtin.debug:
        msg: "Deploying for {{ company_name }} at {{ company_domain }}"
